version: '2.1'
jobs:
  build:
    docker:
      - image: cimg/node:15
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - store_test_results:
          path: test-results/jest
          destination: results.xml
