version: '2.1'
orbs:
  node: circleci/node@16.13
jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  test_my_app:
    jobs:
      - node/test:
          test-results-for: jest
