version: '2.1'
jobs:
  build:
    docker:
      - image: cimg/node:19.5.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - store_test_results:
          path: test-results/jest
