version: '2.1'
jobs:
  build:
    docker:
      - image: circleci/node@16.13
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  test_my_app:
    jobs:
      - node/test:
          test-results-for: jest
